### ISSUE TITLE
Describe Should Work With Queries

### ISSUE THREAD

**Issue by drcapulet** [square/metrics#214]
It'd be awesome to be able to do this:

```
describe `a.b.c` | transform.rate
```

**Comment by Nathan-Fenner** [comment]
It would probably be more straightforward to instead add descriptions to all `select` queries. As long as you're only interested in the tags from the resulting series rather than the queried series (so, for example, `metric | aggregate.sum(group by datacenter) from -2hr to now` would only have datacenter tags) then this would be very simple the implement.

The main challenge in adding this information to `select` is that in the JSON representation, `select` is just a list- so there's no place for us to put the extra data without changing the API.

Also, would it be better to use the existing `describe` behavior, which produces a `map[Key][]Value`, or the more direct behavior, which produces a `[]map[Key]Value`?

**Comment by Nathan-Fenner** [comment]
It's now possible to get description information from a `select` statement, through the `metadata` field in the JSON response: `response.metadata.description` from a select statement has the same form as the body of a describe statement.
